services:
  - type: web
    name: line-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: python app.py
    envVars:
      - key: LINE_CHANNEL_ACCESS_TOKEN
        value: "your_access_token"
      - key: LINE_CHANNEL_SECRET
        value: "your_channel_secret"

